export const ROLES = {
  CLIENT: "client",
  MODERATOR: "moderator",
  ADMIN: "admin",
  SUPER_ADMIN: "super_admin",
};

export const AD_STATUSES = {
  DRAFT: "Draft",
  SUBMITTED: "Submitted",
  UNDER_REVIEW: "Under Review",
  PAYMENT_PENDING: "Payment Pending",
  PAYMENT_SUBMITTED: "Payment Submitted",
  PAYMENT_VERIFIED: "Payment Verified",
  SCHEDULED: "Scheduled",
  PUBLISHED: "Published",
  EXPIRED: "Expired",
  REJECTED: "Rejected",
};

export const PAYMENT_STATUSES = {
  PENDING: "pending",
  SUBMITTED: "submitted",
  VERIFIED: "verified",
  REJECTED: "rejected",
};

export const MEDIA_TYPES = {
  IMAGE: "image",
  YOUTUBE: "youtube",
};

export const VALIDATION_STATUSES = {
  PENDING: "pending",
  VALID: "valid",
  INVALID: "invalid",
};

export const PUBLIC_AD_STATUSES = [AD_STATUSES.PUBLISHED];

export const STATUS_TRANSITIONS = {
  [AD_STATUSES.DRAFT]: [AD_STATUSES.SUBMITTED],
  [AD_STATUSES.SUBMITTED]: [AD_STATUSES.UNDER_REVIEW],
  [AD_STATUSES.UNDER_REVIEW]: [AD_STATUSES.PAYMENT_PENDING, AD_STATUSES.REJECTED],
  [AD_STATUSES.PAYMENT_PENDING]: [AD_STATUSES.PAYMENT_SUBMITTED],
  [AD_STATUSES.PAYMENT_SUBMITTED]: [AD_STATUSES.PAYMENT_VERIFIED],
  [AD_STATUSES.PAYMENT_VERIFIED]: [AD_STATUSES.SCHEDULED, AD_STATUSES.PUBLISHED],
  [AD_STATUSES.SCHEDULED]: [AD_STATUSES.PUBLISHED, AD_STATUSES.EXPIRED],
  [AD_STATUSES.PUBLISHED]: [AD_STATUSES.EXPIRED],
  [AD_STATUSES.REJECTED]: [AD_STATUSES.DRAFT],
};

export const DEFAULT_PLACEHOLDER_IMAGE =
  "https://images.unsplash.com/photo-1516321497487-e288fb19713f?auto=format&fit=crop&w=1200&q=80";

export const WORKFLOW_LABELS = [
  AD_STATUSES.DRAFT,
  AD_STATUSES.SUBMITTED,
  AD_STATUSES.UNDER_REVIEW,
  AD_STATUSES.PAYMENT_PENDING,
  AD_STATUSES.PAYMENT_SUBMITTED,
  AD_STATUSES.PAYMENT_VERIFIED,
  AD_STATUSES.SCHEDULED,
  AD_STATUSES.PUBLISHED,
  AD_STATUSES.EXPIRED,
];
